### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by Arithmomaniac** [sboulema/CodeNav#46]
I was expecting a large update from the 4.0 bump, and was surprised to find just minor improvements. Have you considered using [Semantic Versioning](https://medium.com/@u_glow/making-sense-of-semantic-versioning-for-end-user-software-applications-a3049d97478b)?

**Comment by sboulema** [comment]
I was just changing the version +0.1 every release and not using semantic versioning :p 

Anyway very good suggestion and will use semantic versioning from now on. 👍 

The 4.0 release does warrant the version bump because the filter options have been refactored and any previously set up filters for code items in CodeNav (eg. hiding methods or protected items) will be lost and have to be reset with this version of CodeNav.
